# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d943f2223d080e3810fe4db2f58b5dcc84a50bdb8ef46fb1887aa3f95b29fd3f0c616a87bc604703237d4b434554d88fd491d5055d75ac0d3c3bdbd442b625a

test:
  secret_key_base: d0d57bf3b73dfd9ada112c2b1d5dd00fdd77d2949a992f37d98a18a87ad1d47474f73b1bbe99af2dfaad586b05f5573d2a0046005c877004dada08aa367af3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
